apiVersion: v1
entries:
  application_helm:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-13T10:45:48.6799792+05:30"
    dependencies:
    - condition: foo.enabled
      name: todo-api-h2
      repository: https://vijaynvb.github.io/todoapi/Helm/TodoApi_H2/charts
      version: 0.1.0
    - condition: foo.enabled
      name: todo-api
      repository: https://vijaynvb.github.io/todoapi/Helm/TodoApi_MySQL/todoapp/charts
      version: 0.1.0
    description: A Helm chart for to deploy multiple microservices
    digest: 6906d9959f06e6700f536ec57b78984edad77ab8365da4f996a2442447578d16
    name: application_helm
    type: application
    urls:
    - application_helm-0.1.0.tgz
    version: 0.1.0
  todo-api:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-12-13T10:45:48.6804832+05:30"
    dependencies:
    - condition: database.enabled
      name: mysql
      repository: https://vijaynvb.github.io/todoapi/Helm/TodoApi_MySQL/mysql/charts
      version: 0.1.0
    description: A Helm chart for deploy todo application
    digest: f31f34dfa10bb69aef6c5a5fe7afd6ede3c6cbc5b11955df20d252aec881f1d9
    name: todo-api
    type: application
    urls:
    - todo-api-0.1.0.tgz
    version: 0.1.0
  todo-api-h2:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-12-13T10:45:48.680576+05:30"
    description: A Helm chart for deploy todo application
    digest: 4b74a0de519925c41dab6205d62826ed5258b9e7e66b6cc96e1e2d535a4093ac
    name: todo-api-h2
    type: application
    urls:
    - todo-api-h2-0.1.0.tgz
    version: 0.1.0
generated: "2023-12-13T10:45:48.6787687+05:30"
